version: "3.7"

# For local development, only database is running
#
# docker-compose up -d
# uvicorn app.main:app --reload
#

services:
  database:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:5432"
volumes:
  database_data:
