"""add-vending

Revision ID: 857b05b905dd
Revises: 09cebb25c784
Create Date: 2024-01-30 15:17:27.361035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "857b05b905dd"
down_revision = "09cebb25c784"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "vending_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("users", "vending_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "vending_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("products", "vending_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
