"""add-vending

Revision ID: e2268d50bdc4
Revises: 65bf86b7c644
Create Date: 2024-01-30 15:04:04.131020

"""
from alembic import op
import sqlalchemy as sa
from app.core.config import settings

# revision identifiers, used by Alembic.
revision = "e2268d50bdc4"
down_revision = "65bf86b7c644"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vending_machines",
        sa.Column("status", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "products", ["id"])
    # insert record to vending_machines table
    # use settings.VENDING_MACHINE_ID
    op.execute(
        f"""
        INSERT INTO vending_machines (id, status, created_at, updated_at) VALUES ('{settings.VENDING_MACHINE_ID}', '{{"1": 10, "2": 10, "5": 10, "10": 10}}', now(), now())
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="unique")
    op.drop_table("vending_machines")
    # ### end Alembic commands ###
